### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by qqsh0214** [GeorgeSeif/Semantic-Segmentation-Suite#2]
@GeorgeSeif Thanks for your code! I use my own dataset and don't change other hyper parameters. While training, I meet the following error.

[2018-01-08 14:49:35] Epoch = 0 Count = 640 Current = 0.44 Time = 1.12
Traceback (most recent call last):
  File "main.py", line 155, in <module>
    input_image, output_image = utils.random_crop(input_image, output_image, args.crop_height, args.crop_width)
  File "/home/linxp/zhangch/fc-DenseNet/utils.py", line 61, in random_crop
    return image[y:y+crop_height, x:x+crop_width, :], label[y:y+crop_height, x:x+crop_width]
IndexError: too many indices for array

I can't figure out the reason.There is no problem for CamVid dataset because the training set has only 360 samples. However, my training set has about 1500 samples for 2 classses. It fails at about 600 steps for the above error. Could you give some suggestion?

**Comment by GeorgeSeif** [comment]
Hi there,

So the "IndexError: too many indices for array" means that you are essentially passing too much data to the array. Think of it this way: You are passing 3 values to the image array (i.e the range to crop), BUT this is assuming the array has a 3rd dimension (i.e it is a colour image). If your data happens to be a grayscale image, or maybe the data isn't read in properly (bad file name, corrupted file), then an IndexError like this would be thrown!

I would try checking out your data. Possibly some are grayscale or corrupted. Also check that the files are being read in properly. 

This may also be a good catch that this should be updated to deal with grayscale inputs!

Thank you for the feedback on the code and let me know how things progress!

**Comment by GeorgeSeif** [comment]
One more thing to add. The fact that the training gets through 600 steps means that the program was able to go through many images before throwing that error. That could be an indication that the image file (whether the name for reading it in or the file itself) is causing a problem!

**Comment by qqsh0214** [comment]
Thanks for your advice. The images in my dataset are all RGB 3-D pictures and labels are all 1-D. So maybe the data isn't read in properly. I change all my images from JPG to PNG and make sure that there is a consistent one-to-one match between images and labels. And it can be trained smoothly now.

By the way , when testing,  the images are also cropped into 256*256, so we can't get a segmentation result the same size(i.e 360*480) as orignal. How can I realize this?

**Comment by GeorgeSeif** [comment]
Okay, good to hear!

So, the reason for this crop size is because many segmentation networks will have some downsampling. Now lets say for example a network has 4 pooling layers; this means eventually the input will have it's size divided by 2, 4 times. If the input is of size 360x480, we would end up doing 360/2/2/2/2 (divide by 2 4 times), which gets us 22.5. Unfortunately, TensorFlow would actually **round** this to 23. Then, when we upsample 4 times we get 23*2*2*2*2 = 368!

That's why you can set the crop size as an input argument! If you want to be able to handle images with a dimension of 360, you would need to set the crop size of that dimension to 352, since that's the biggest dimension within 360 that is divisible by 2, 4 times. 

I.e you need to set the crop size to be closest to the original size as possible. Inevitably, with some networks there **must** be some cropping. If the network has **no downsampling whatsoever**, then you can just go ahead and set the crop size to the original image size.

**Comment by qqsh0214** [comment]
Thanks for your detailed analysis! That really makes sense. Just crop the image as 352 * 480 and it can work.

**Comment by GeorgeSeif** [comment]
No problemo!
