### ISSUE TITLE
image size in prediction mode

### ISSUE THREAD

**Issue by crisnv** [GeorgeSeif/Semantic-Segmentation-Suite#27]
Hello,

is the code prepared for predicting images of any size?

Very helpful code by the way...

**Comment by GeorgeSeif** [comment]
Sort of:

Many segmentation networks will have some downsampling. Now lets say for example a network has 4 pooling layers; this means eventually the input will have it's size divided by 2, 4 times. If the input is of size 150x150, we would end up doing 150/2/2/2/2 (divide by 2 4 times), which gets us 9.375. Unfortunately, TensorFlow would actually round this to 9. Then, when we upsample 4 times we get 9x2x2x2x2 = 144 which is different from your final label size! It'll actually mess things up even earlier during upsampling, as what happened in your case. 

That's why you can set the crop size as an input argument! If you want to handle images of different size with the FC-DenseNet which has 5 pooling layers, you will need an image size that is divisible by 2^5 = 32.If the network had no downsampling whatsoever, then you can just go ahead and set the crop size to the original image size.
