### ISSUE TITLE
Trained parameters for all models

### ISSUE THREAD

**Issue by zengzhi2015** [GeorgeSeif/Semantic-Segmentation-Suite#57]
Hi, friend! Thanks a lot for your work. I have a little suggestion regarding all models. I found that the image reading and augmentation speed is very low and hence the training time is long. It would be very appreciated if you would like to provide us with the trained parameters of all complete models (not ResNets alike, but the whole model) as checkpoint files.

**Comment by GeorgeSeif** [comment]
I appreciate the kind words :)

As for pre-trained models, I won't be adding those, simply because segmentation tasks tend to be quite different, meaning that most data sets are quite different.

Plus... I don't have a GPU right now unfortunately! I don't think training should take too long though. When I had my 1080Ti a day of training was enough for CamVid.
