### ISSUE TITLE
GPU required

### ISSUE THREAD

**Issue by RomRoc** [GeorgeSeif/Semantic-Segmentation-Suite#8]
Hello, I executed your interesting repository in my computer, but after some minutes I get error:
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,168960,2160] and ...

Do you think it depends on my computer that has only 4GB and hasn't a GPU?

Can I change default settings in main.py to execute your code in my computer, or I need to run in a instance in the cloud (Aws) with GPU? 

Thanks a lot

**Comment by GeorgeSeif** [comment]
Hi there!

You are correct that the "ResourceExhaustedError" comes from running out of memory. May I ask which model are you using? What's your batch size? Using a smaller batch size or a model with less parameters will help lower the memory requirements. Cropping to smaller image size also helps.

But, if you want to use the bigger models, with a bigger sized image, then yes you may need more memory (running on AWS is an option). 4GB isn't too much and some models may not fit in the memory, especially since if you're using your regular RAM (and not GPU memory) you'll have other programs using up some of that space.

I hope that helps and let me know how it goes! :)

**Comment by RomRoc** [comment]
Hello, 
thanks for your answer. First time I executed main.py with all the default parameters, so it is FC-DenseNet103 model and batch_size = 1. The training couldn't even start for lack of resources.
Yesterday I executed with FC-DenseNet56 model, in this case the training started but after some hours it stopped to work.
I should use a proper computer with GPU and more ram.

Thanks

**Comment by GeorgeSeif** [comment]
Yup, that sounds right!

**Comment by RomRoc** [comment]
Could I know please the annotation tool you suggest to use, to create my own training dataset?
Maybe [LabelMe](https://github.com/CSAILVision/LabelMeAnnotationTool) ?
Thanks

**Comment by GeorgeSeif** [comment]
I've never used one actually! CamVid is one that's commonly used in research though.

LabelMe looks pretty good. Anything that comes from a reputable research group like MIT CSAIL should be a good bet!
